### ISSUE TITLE
Add pydantic to parse incoming events

### ISSUE THREAD

**Issue by elmsdata** [cdevents/sdk-python#12]
@erkist outlined, the next enhancement to the Python SDK would be to parse incoming events! Like in the CloudEvents Python SDK, they use [Pydantic](https://github.com/cloudevents/sdk-python/tree/main/cloudevents/pydantic) used for data parsing and validation. Issue is to track changes (for future changelog), conversations outside the pull request and any other feedback/input from the community!

**Comment by AshitaSingamsetty** [comment]
I would like to work on this and will raise a PR.

**Comment by AshitaSingamsetty** [comment]
I would like to work on this and will raise a PR.

**Comment by elmsdata** [comment]
> I would like to work on this and will raise a PR.

Thanks Ashita for taking up this request, let me know if I can help with anything!
