### ISSUE TITLE
Update License file to add copyright owner

### ISSUE THREAD

**Issue by bradmccoydev** [cdevents/sdk-python#26]
**Good first issue**

In the license file on line 189 the authors haven't been stated, this is a common thing that people miss when adding apache2 licenses.

change text to: 
```
Copyright 2023 The cdevents Authors
```

**Comment by FourAndHalf** [comment]
Okay could you assign it to me

**Comment by bradmccoydev** [comment]
I cant sorry as im not an admin on this repo but feel free to work on it as people will see in the comments you are

**Comment by FourAndHalf** [comment]
okay

**Comment by afrittoli** [comment]
> Okay could you assign it to me

Done - thanks for helping!
